# Generated by Django 4.2 on 2024-05-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0003_alter_memory_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='memory',
        ),
        migrations.AddField(
            model_name='memory',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places_remember.coordinates'),
        ),
    ]
