# Generated by Django 4.2 on 2024-05-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember', '0005_remove_memory_coordinates_memorycoordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='memories',
        ),
        migrations.AddField(
            model_name='memory',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places_remember.coordinates'),
        ),
        migrations.DeleteModel(
            name='MemoryCoordinates',
        ),
    ]
